Move the system configuration to be controlled by an environment variable file.

diff --git a/etc/init.d/caduceus b/etc/init.d/caduceus
--- a/etc/init.d/caduceus
+++ b/etc/init.d/caduceus
@@ -10,11 +10,44 @@
 # Source function library
 . /etc/rc.d/init.d/functions
 
+# Source the optional environment setup file
+if [ -f /etc/caduceus/caduceus.env ]; then
+	. /etc/caduceus/caduceus.env
+fi
+
 RETVAL=0
-DAEMON_COREFILE_LIMIT=unlimited
 
 # Set limits here in addition to limits.conf
-ulimit -n 65535
+#-------------------------------------------------------------------------------
+if [ -n "$ULIMIT_OPEN_FILES" ]; then
+	sysctl -w fs.file-max=$ULIMIT_OPEN_FILES > /dev/null
+	RETVAL=$?
+	[ $RETVAL -ne 0 ] && echo "fs.file-max=$ULIMIT_OPEN_FILES failed" && exit $RETVAL
+
+	sysctl -w fs.nr_open=$ULIMIT_OPEN_FILES > /dev/null
+	RETVAL=$?
+	[ $RETVAL -ne 0 ] && echo "fs.nr_open=$ULIMIT_OPEN_FILES failed" && exit $RETVAL
+
+	ulimit -n $ULIMIT_OPEN_FILES > /dev/null
+	RETVAL=$?
+	[ $RETVAL -ne 0 ] && echo "ulimit -n $ULIMIT_OPEN_FILES failed" && exit $RETVAL
+fi
+if [ -n "$NET_IPV4_TCP_MEM" ]; then
+	sysctl -w net.ipv4.tcp_mem=$NET_IPV4_TCP_MEM > /dev/null
+	RETVAL=$?
+	[ $RETVAL -ne 0 ] && echo "net.ipv4.tcp_mem=$NET_IPV4_TCP_MEM failed" && exit $RETVAL
+fi
+if [ -n "$NET_CORE_SOMAXCONN" ]; then
+	sysctl -w net.core.somaxconn=$NET_CORE_SOMAXCONN > /dev/null
+	RETVAL=$?
+	[ $RETVAL -ne 0 ] && echo "net.core.somaxconn=$NET_CORE_SOMAXCONN failed" && exit $RETVAL
+fi
+if [ -n "$NET_IPV4_TCP_MAX_SYN_BACKLOG" ]; then
+	sysctl -w net.ipv4.tcp_max_syn_backlog=$NET_IPV4_TCP_MAX_SYN_BACKLOG > /dev/null
+	RETVAL=$?
+	[ $RETVAL -ne 0 ] && echo "net.ipv4.tcp_max_syn_backlog=$NET_IPV4_TCP_MAX_SYN_BACKLOG failed" && exit $RETVAL
+fi
+#-------------------------------------------------------------------------------
 
 start() {
 	echo -n $"Starting caduceus: "
